from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (QApplication, QWidget, QMessageBox, QLabel, QPushButton, QVBoxLayout, QHBoxLayout, QLineEdit)

app = QApplication([])
class Okno1(QWidget):
    def __init__(self):
        super().__init__()
        self.label1 = QLabel('буква1')
        self.label2 = QLabel('буква2')
        self.but1 = QPushButton('knopka1')
        self.v1 = QVBoxLayout()
        self.v1.addWidget(self.label1)
        self.v1.addWidget(self.label2)
        self.v1.addWidget(self.but1)
        self.setLayout(self.v1)
window = Okno1()
window.show()
app.exec_()
class Okno2(QWidget):
    def __init__(self):
        super().__init__()
        self.label11 = QLabel('буквы1')
        self.lineedit1 = QLineEdit('vvod1')
        self.label22 = QLabel('буквы2')
        self.lineedit2 = QLineEdit('vvod2')
        self.label3 = QLabel('буквы3')
        self.but2 = QPushButton('knopka2')
        self.lineedit3 = QLineEdit('vvod3')
        self.label4 = QLabel('буквы4')
        self.but3 = QPushButton('knopka3')
        self.label5 = QLabel('буквы5')
        self.but4 = QPushButton('knopka4')
        self.lineedit4 = QLineEdit('vvod4')
        self.lineedit5 = QLineEdit('vvod5')
        self.v2 = QVBoxLayout()
        self.v2.addWidget(self.label11)
        self.v2.addWidget(self.lineedit1)
        self.v2.addWidget(self.label22)
        self.v2.addWidget(self.lineedit2)
        self.v2.addWidget(self.label3)
        self.v2.addWidget(self.but2)
        self.v2.addWidget(self.lineedit3)
        self.v2.addWidget(self.label4)
        self.v2.addWidget(self.but3)
        self.v2.addWidget(self.label5)
        self.v2.addWidget(self.but4)
        self.v2.addWidget(self.lineedit4)
        self.v2.addWidget(self.lineedit5)
        self.setLayout(self.v2)

but2.clicked.connect(Okno2)
window1 = Okno2()
window1.show()
app.exec_()